name = "minetools"
main = "worker.js"
compatibility_date = "2026-03-22"

# Keep workers.dev enabled unless you are deploying to a custom route.
workers_dev = false

[[kv_namespaces]]
binding = "PROFILE_CACHE"
id = "32a71a2c083e42f7bee7b40eb75c1ea6"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 120, period = 60 }